# Gradle 명령의 기본 메모리. 사용자나 명령줄 속성으로 덮어쓸 수 있다.
# 마인크래프트 디컴파일에 필요한 메모리를 확보하기 위해 필요하다.
org.gradle.jvmargs=-Xmx6G -Xss4m
org.gradle.daemon=false

# 모드
mod_id=advancednetherite
mod_version=2.4.2
mod_name=Advanced Netherite
mod_author=Autovw

# 마인크래프트
minecraft_version=26.2



# Fabric
fabric_loader_version=0.19.3
fabric_api_version=0.154.2+26.2



# Fabric 모드 의존성
detailab_fabric_version=5837572
catalogue_fabric_version=5303331
configured_fabric_version=5441234
jei_fabric_version=5466549

