# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false

# Mod
mod_id=advancednetherite
mod_version=2.4.2
mod_name=Advanced Netherite
mod_author=Autovw

# Minecraft
minecraft_version=26.2



# Fabric
fabric_loader_version=0.19.3
fabric_api_version=0.154.2+26.2



# Fabric mod dependencies
detailab_fabric_version=5837572
catalogue_fabric_version=5303331
configured_fabric_version=5441234
jei_fabric_version=5466549

