org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
loom.ignoreDependencyLoomVersionValidation=true

project.libs=26.2-SNAPSHOT
project.platforms=Common, Fabric
project.plugins=1.1-SNAPSHOT

# 설치된 모드팩과 호환되도록 컴파일과 실행 요구 사항을 맞춘다.
project.libs.versions.fabricapi.min=0.156.0
project.libs.versions.fabricapi.version=0.156.0+26.2
project.libs.versions.puzzleslib.min=26.2.1
project.libs.versions.puzzleslib.version=26.2.1

mod.authors=Dricky, Safro, Zeckemith, Fuzs
mod.description=The illagers are back! Be ready to fight new foes. A port of Illager Expansion.
mod.group=fuzs.illagerinvasion
mod.id=illagerinvasion
mod.license=MIT
mod.name=Illager Invasion
mod.version=26.2.0

dependencies.common.multiloaderdataextensions=embedded
dependencies.fabric.fabricapi=required
dependencies.fabric.forgeconfigapiport=required
dependencies.fabric.puzzleslib=required

distributions.curseforge.id=891324
distributions.curseforge.slug=illager-invasion
distributions.github.slug=illager-invasion
distributions.modrinth.id=jSV9w0J5
distributions.modrinth.slug=illager-invasion

environments.client=required
environments.server=required
