plugins {
    id "com.gradleup.shadow"
}

architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath
}

configurations {
    common
    shadowCommon // shadow 플러그인의 shadow는 파일을 *제외*하므로 쓰지 않는다.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

dependencies {
    implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    api "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
    // API에 의존하지 않으려면 다음 줄을 지운다
    api "dev.architectury:architectury-fabric:${rootProject.architectury_version}"

    common(project(path: ":common", configuration: "runtimeElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionFabric")) { transitive false }
}

processResources {
    var replaceProperties = [
            "version": project.version,
            "mod_id": project.mod_id,
            "mod_name": project.mod_name,
            "mod_description": project.mod_description,
            "mod_author": project.mod_author,
            "mod_license": project.mod_license,
            "mod_website": project.mod_website,
            "mod_repository": project.mod_repository,

            "fabric_loader_version": project.fabric_loader_version,
            "fabric_api_version": project.fabric_api_version,
            "minecraft_version": project.minecraft_version,
            "java_version": project.java_version,
            "architectury_version": project.architectury_version,
    ]
    inputs.properties replaceProperties

    filesMatching(['fabric.mod.json']) {
        expand replaceProperties
    }
}

shadowJar {
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "fabric"
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

sourcesJar {
    archiveClassifier = "fabric-sources"
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {
    publications {
        mavenFabric(MavenPublication) {
            artifactId = rootProject.archives_base_name + "-" + project.name
            from components.java
        }
    }

    // 배포 설정 방법은 https://docs.gradle.org/current/userguide/publishing_maven.html 참고.
    repositories {
        // 배포할 저장소는 여기에 넣는다.
    }
}


