org.gradle.jvmargs=-Xmx4096M
org.gradle.daemon=false
java_version=25

enabled_platforms=fabric
maven_group=com.daqem
archives_base_name=uilib

# Project
mod_version=2.1.4-26.2
mod_id=uilib
mod_name=UI Lib
mod_description=An easy-to-use library for creating user interfaces in Minecraft.
mod_author=
mod_license=Apache-2.0
mod_website=
mod_repository=

# Publishing
supported_minecraft_versions=26.2
release_type=release

curse_forge_project_id=933200
curseforge_dependencies=architectury-api

modrinth_project_id=AOEDs9Al
modrinth_dependencies=architectury-api

# Minecraft
minecraft_version=26.2

# Fabric
fabric_loader_version=0.19.3
fabric_api_version=0.154.2+26.2


# NeoForge
neoforge_version=26.2.0.37-beta
neoforge_loader_version=1

# Dependencies
architectury_version=21.0.6

# Testing
j_unit_version=5.9.3
