architectury {
    common(rootProject.enabled_platforms.split(","))
}

loom {
    accessWidenerPath = file("src/main/resources/uilib.accesswidener")
}

dependencies {
    // Fabric @Environment 어노테이션과 Mixin 의존성을 쓰기 위해 여기서 Fabric 로더에 의존한다
    // Fabric 로더의 다른 클래스는 쓰지 않는다
    implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    // API에 의존하지 않으려면 다음 줄을 지운다
    api "dev.architectury:architectury:${rootProject.architectury_version}"

}

publishing {
    publications {
        mavenCommon(MavenPublication) {
            artifactId = rootProject.archives_base_name
            from components.java
        }
    }

    // 배포 설정 방법은 https://docs.gradle.org/current/userguide/publishing_maven.html 참고.
    repositories {
        // 배포할 저장소는 여기에 넣는다.
    }
}
