architectury {
    common rootProject.enabled_platforms.split(",")
}

loom {
    accessWidenerPath = file("src/main/resources/itemrestrictions.accesswidener")
}

dependencies {
    // We depend on fabric loader here to use the fabric @Environment annotations and get the mixin dependencies
    // Do NOT use other classes from fabric loader
    implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    // Remove the next line if you don't want to depend on the API
    api "dev.architectury:architectury:${rootProject.architectury_version}"
    //source: https://github.com/Fuzss/forgeconfigapiport-fabric

    testImplementation "org.junit.jupiter:junit-jupiter-api:${rootProject.jUnitVersion}"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:${rootProject.jUnitVersion}"

    implementation files(rootProject.file("../YamlConfig-26.2/fabric/build/libs/yamlconfig-1.3.2-26.2-fabric.jar"))
    implementation files(rootProject.file("../ArcLib-26.2/fabric/build/libs/arc-1.9.7-26.2-fabric.jar"))
}
