org.gradle.jvmargs=-Xmx4096M
org.gradle.daemon=false
java_version=25

enabled_platforms=fabric
maven_group=com.daqem
archives_base_name=yamlconfig

# Project
mod_version=1.3.2-26.2
mod_id=yamlconfig
mod_name=YAML Config
mod_description=A Minecraft configuration mod based on the YAML file format.
mod_author=
mod_license=Apache-2.0
mod_website=
mod_repository=

# Publishing
supported_minecraft_versions=26.2
release_type=release

curse_forge_project_id=1128669
curseforge_dependencies=architectury-api,ui

modrinth_project_id=L1FFB418
modrinth_dependencies=architectury-api,ui-lib

# Minecraft
minecraft_version=26.2

# Fabric
fabric_loader_version=0.19.3
fabric_api_version=0.154.2+26.2

# NeoForge
neoforge_version=26.2.0.37-beta
neoforge_loader_version=1

# Dependencies
architectury_version=21.0.6

ui_library_version=2.1.4-26.2
ui_library_file_fabric=7061587
ui_library_file_fabric_sources=7061588
ui_library_file_neoforge=7061589
