apply plugin: 'com.gradleup.shadow'

architectury {
    common rootProject.enabled_platforms.split(",")
}

loom {
    accessWidenerPath = file("src/main/resources/yamlconfig.accesswidener")
}

dependencies {
    // We depend on fabric loader here to use the fabric @Environment annotations and get the mixin dependencies
    // Do NOT use other classes from fabric loader
    modImplementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    modImplementation "dev.architectury:architectury:${project.architectury_version}"

    modImplementation "org.snakeyaml:snakeyaml-engine:2.7"
    modImplementation files(rootProject.file("../UILib-26.2/fabric/build/libs/uilib-2.1.4-26.2-fabric.jar"))
}
